name: Deploy Flask Application to EC2

on:
  push:
    branches:
      - test-1 # Adjust this as per your requirement

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            rm -rf *
            git clone https://github.com/TrickSumo/langchain-course-python.git
